### ISSUE TITLE
idea for eliminating s_appdata global

### ISSUE THREAD

**Issue by witten** [kmwoley/onebusaway-pebbletime#2]
If you wanted to eliminate the `s_appdata` global in `main.c`, you could pass it in as a parameter to each of `HandleInit()` and `HandleDeinit()`. If you did that, `main()` would look something like this:

```
int main(void) {
  AppData appdata;
  HandleInit(&appdata);
  app_event_loop();
  HandleDeinit(&appdata);
}
```

Of course, that only works if there's not some SDK-dictated reason why the variable has to be a static global.

Feel free to close if this is not a thing you want to do.

**Comment by kmwoley** [comment]
Thanks. I'm interested in your thoughts on the rest of the globals littered throughout. I'm contemplating the value in reducing/eliminating globals throughout the rest of the code. This was an easy/simple example.

**Comment by witten** [comment]
Some thoughts about the other globals:

Looking at `bus_details.c` as a representative example, some of the globals may be unavoidable based on the Pebble UI library you're using. For instance, the signature `WindowLoad` doesn't take any parameters other than the `Window`, so it's not like you can pass in a bunch of other arguments and make it super explicit what values the function uses. However, this is a function called [`window_set_user_data()`](https://developer.pebble.com/docs/c/User_Interface/Window/#window_set_user_data) that allows you to attach your own arbitrary data to the window for this sort of use case. That way you can stuff a bunch of state into a struct and eliminate globals for anything that's related to a window or window handler. That at least explicitly scopes your values to the functions that need to consume them.

Similarly, if you have any control over the callback context that some of the UI library callbacks pass to you, you can stuff your data into them.

One more technique is to lean on the UI library to store state for you since it's doing that anyway. For instance, if you need the root layer in some function, you can just query the UI library for it, rather than having to store it yourself.

Finally, for globals that are really unavoidable with the Pebble UI library, your best bet is to "wall off" the areas of code that deal with UI so that they don't infect your business logic or persistence layers. This is good practice in general, all globals aside. I realize that in this particular app, most of the code is UI code!
