### ISSUE TITLE
Add app settings for minutesBefore, minutesAfter

### ISSUE THREAD

**Issue by kmwoley** [kmwoley/onebusaway-pebbletime#22]
http://developer.onebusaway.org/modules/onebusaway-application-modules/current/api/where/methods/arrivals-and-departures-for-stop.html

**Comment by barbeau** [comment]
We default to 65 min for minutesAfter on most platforms. This is enough to capture buses with a headway of 1hr, assuming they aren't running too late.

**Comment by barbeau** [comment]
And I don't think any of the clients submit minutesBefore by default.

**Comment by kmwoley** [comment]
Thanks for the details. Due to the small screen size I've found the -5 / 35
min defaults to be pretty good, However I think there is good reason to
allow a user to adjust it.

**Comment by barbeau** [comment]
Yeah, it's definitely a balancing act.  Go with whatever you think is best on Pebble.

**Comment by kmwoley** [comment]
So far, no complaints about the default config. Closing this enhancement until I get feedback from users that it would be useful.
