### ISSUE TITLE
Use Regions API instead of hard-coded regions list

### ISSUE THREAD

**Issue by barbeau** [kmwoley/onebusaway-pebbletime#26]
Just wanted to make sure you knew about the Regions API:
* http://regions.onebusaway.org/regions-v3.json
* http://regions.onebusaway.org/regions-v3.xml

It's a centralized API to dynamically pull back a list of supported OBA regions, including their geographic boundaries and server APIs.  [Documentation](https://github.com/OneBusAway/onebusaway/wiki/Multi-Region#regions-rest-api) for this is hosted separately from the central OBA docs (we need to fix this), so some devs miss it.

I know there are constraints to thinks about for low-resource devices and yet-another-API-call, so if you're already considered this and chosen the hard-coded server config then feel free to close the issue, but if you didn't know about it you might want to check it out.

**Comment by kmwoley** [comment]
I looked at leveraging the Regions API when I first implemented multi-region support. However, it wasn't clear that there was an advantage to using it given that I had to hardcode each region's API key. As I was hardcoding the API keys, it was easier to add the service URL and location data as part of the hardcoding.

Is there a better pattern when using the Regions API?

**Comment by barbeau** [comment]
All regions are expected to support your same API key (this is how all the other official OBA apps work, and some 3rd party multi-region apps) - you'll just need to ask each region directly to add your specific key via email (please copy me too).  You should be able to use the `contactEmail` field email address in the Regions API results to reach each region via email.

More info at https://github.com/OneBusAway/onebusaway-application-modules/wiki/API-Webapp-Configuration-Guide#new-3rd-party-mobile-apps---api-key-generation-and-sharing-process.

**Comment by kmwoley** [comment]
Fascinating. That's good that there's a key-sharing process; that wasn't clear when I was setting up my multi-region support. That makes a lot more sense.

Funny that this didn't come up as I was requesting specific API keys from each of the regions. Given the pain that it was to get each to generate a key, I'm hesitant to go back to them and ask them to add my key before the app is 'official'.

I think the best path forward would be to generate an official Pebble OneBusAway key, [publish it to the docs like the other apps](https://github.com/OneBusAway/onebusaway-application-modules/wiki/API-Webapp-Configuration-Guide#using-the-official-oba-mobile-apps-with-your-oba-server), and then do as you suggest to to get the regions to add the key to their servers.

If I'm doing that from the pebble@onebusaway.org email address as an official app hopefully that will make the process go quickly/smoothly.

What do you think?

**Comment by barbeau** [comment]
Yeah, I think waiting until official adoption is best approach. You could
even ship v1.0 with hard coded regions and patch later.

Pebble@onebusaway.org would just be a distribution list, so couldn't send
mail,  but we could set you up with @onebusaway.org email if you'd like.
Either way, I agree that it will be easier to get more traction after
adoption.

**Comment by kmwoley** [comment]
Moved to https://github.com/OneBusAway/onebusaway-pebbletime/issues/9
